### ISSUE TITLE
US- Implementação de horários fixos para envio de notificação através do app 

### ISSUE THREAD

**Issue by joaovitor26** [proepidesenvolvimento/guardioes-app#103]
**Descrição (Como [quem], eu quero [o quê] para [por quê]?)**<br>

Como parte do grupo de comunicação do Guardiões da saúde, após a análise e interpretação dos dados de registros dos usuários no aplicativo, observei que há horários fixos em que os usuários mais acessam o aplicativo. Diante disso, sugere-se uma estratégia para aumentar o engajamento dos usuários, através do envio de notificações em horários específicos e a todos os usuários. 
O relatório que apresenta a análise de dados será inserido nesse corpo de texto, a fim de confirmar a hipótese de que horários específicos para notificação poderá aumentar o engajamento. 

https://docs.google.com/document/d/1QPUExS8A0m9O58G5jRtXY2lxx85hD9XbeqeLUFgiBls/edit

**Critérios de aceite**
- [ ] Sugere-se que notificações devem ser enviadas a todos os usuários 
- [ ] Sugere-se que as notificações sejam enviadas nos horários dispostos no relatório
- [ ] Sugere-se que a mensagem que compõe a notificações varie de acordo com o horário de envio

**Comment by Gabriella-Rossetti** [comment]
Notificação

Durante a última semana, a equipe de comunicação realizou uma análise de todos os dados de cadastro dos usuários 
disponíveis no Kibana. Após filtrar os dados por Instituição e/ou matrícula, observamos que **há, pelos menos, 2016 
usuários, estudantes da universidade de Brasília com sua matrícula incompleta ou Instituição ausente.** 
Portanto, iniciaremos no início de Agosto uma campanha para que os usuários completem os dados de registro. 
Para tanto, precisamos que, se possível, uma notificação seja enviada para todos os usuários através do aplicativo
solicitando que eles confiram seus dados de registro. 

**Sugestão de Notificação**

Olá, Guardiões! Muitos usuários estão com dados incompletos. 
Se você é um estudante da Universidade de Brasília, confira seus dados. 
Tê-los completos será fundamental para a atribuição dos créditos. 

Indicação de data/horário para notificação:

Terça (04/08) às 10:00 e às 23:59

**Comment by Gabriella-Rossetti** [comment]
Notificação (2) 

A equipe de comunicação está levantando estratégias que visam melhorar o engajamento dos usuários no aplicativo. 
Após a análise dos dados disponíveis no Kibana, observou-se que as notificações possuem um impacto considerável na quantidade de usuários que reportam diariamente seu estado de saúde. 
Portanto, sugere-se o envio de notificações diárias programadas em horários específicos (ou não) para os usuários através do aplicativo. Essas notificações possuem textos diversos e servirão para lembrar o usuários de responder o app. 
Essas notificações são diferentes daquela enviada diariamente. 

Sugestão de textos, dias e horários para notificação:

**Notificação 1**
Quando: diariamente 
Horário: 10h
Texto: Ei, não se esqueça de mim! Registre seu estado de saúde. 

**Notificação 2**
Quando: em dias que forem disponibilizados boletins epidemiológicos ou institucionais. Em geral, **quartas e sextas**. 
Horário: 18h
Texto: Confira agora, no nosso Twitter, o Boletim Epidemiológico/ Institucional que você ajudou a construir! 

**Notificação 3**
Quando: diariamente 
Horário: 22h
Texto: Já é quase meia-noite, mas ainda da tempo de registrar seu estado de saúde. Corre para o app!
