### ISSUE TITLE
BUG(Participações sumiram do mapa)

### ISSUE THREAD

**Issue by juvenaljuniorrr** [proepidesenvolvimento/guardioes-app#120]
Apesar desse gráfico pizza, a participações sumiram do mapa, não sei se foi intencional ou não, mas alguns dias estão verdes e outros não

1. Abra o aplicativo
2. Clique em "Diário"
3. As participações não aparecem no calendário

**Comportamento Esperado**<br>
As participações deveriam aparecer no calendário e não só no gráfico

**Screenshot**<br>
![WhatsApp Image 2020-08-04 at 14 11 33](https://user-images.githubusercontent.com/68300937/89323791-aa41dd80-d65c-11ea-9a7d-d0ced2dd6883.jpeg)

 - Modelo do Dispositivo: LGK50S 
 - Versão do Andoird: 9
 - Vesão do App: 3.0.0

**Comment by gabrieldouurado** [comment]
@juvenaljuniorrr o problema persiste na versão do app que está na loja?

**Comment by juvenaljuniorrr** [comment]
> @juvenaljuniorrr o problema persiste na versão do app que está na loja?

Gabriel, apenas uma usuária relatou esse problema: "o aplicativo acabou de fazer atualização, consegui deixar meus dados atualizados certinho, mas os registros não estão todos lá, eu já tinha quase 50 dias contabilizados e agora constam apenas 19"

ajn.reboucas@gmail.com/ 170005470 se puder conferir se ta tudo certo
