### ISSUE TITLE
BUG (Tutorial desatualizado)

### ISSUE THREAD

**Issue by juvenaljuniorrr** [ProEpiDesenvolvimento/guardioes-app#121]
No tutorial do aplicativo a tela de notícias sinaliza um perfil do twitter do Ministério da Saúde e não o twitter do Guardiões. Além disso, os conselhos de saúde e algumas informações do mapa de saúde estão desatualizadas.

Sugestão: adicionar nesse espaço de ajuda algum email do guardiões pro pessoal enviar dúvidas sobre o aplicativo e a concessão dos créditos.

1. Abra o aplicativo
2. Clique na interrogação 

**Comportamento Esperado**<br>

Espera-se informações relacionadas a pandemia de COVID-19 nessa nova atualização.

**Screenshots**<br>

![WhatsApp Image 2020-08-04 at 14 12 04](https://user-images.githubusercontent.com/68300937/89324194-48ce3e80-d65d-11ea-932e-5251e53023f6.jpeg)

![WhatsApp Image 2020-08-04 at 14 12 12](https://user-images.githubusercontent.com/68300937/89324189-45d34e00-d65d-11ea-8a72-ff9d2fa80386.jpeg)

 - Modelo do Dispositivo: LGK50S 
 - Versão do Andoird: 9
 - Vesão do App: 3.0.0

**Comment by jonatas1n** [comment]
Essa **Issue** já foi resolvida. A página referenciada não é mais o perfil no Twitter do Ministério da Saúde, mas o nosso perfil.

**Comment by jonatas1n** [comment]
O problema de referência ao perfil no Twitter do Min. da Saúde já está corrigido.
