### ISSUE TITLE
BUG (Problema com idade)

### ISSUE THREAD

**Issue by juvenaljuniorrr** [proepidesenvolvimento/guardioes-app#122]
Com a atualização da nova versão enviada ontem (03/08/2020) o aplicativo aumentou minha idade para 50 anos. 

1. Abra o aplicativo
2. A idade aparece na página principal do aplicativo errada

Espera-se que a idade seja correspondente a data de nascimento do usuários

![WhatsApp Image 2020-08-04 at 13 13 34](https://user-images.githubusercontent.com/68300937/89324344-859a3580-d65d-11ea-89e0-0de5a3c7710a.jpeg)

**Informações do Dispositivo:**
 - Modelo do Dispositivo: LGK50S e Iphone 7
 - Versão do Android: 9 
-  Versão do iOS: 13.6
 - Vesão do App: 3.0.0

**Comment by gabrieldouurado** [comment]
Problema resolvido na v3.0.0 de produção.
