### ISSUE TITLE
Sugestão (Aba dicas) 

### ISSUE THREAD

**Issue by juvenaljuniorrr** [proepidesenvolvimento/guardioes-app#123]
Na aba "Dicas" os botões estão pouco alinhados. É possível colocar os botões de mesmo tamanho no topo da página que os maiores (os que estão causando desalinhamento) fiquem no final? Outra opção seria organiza-los de modo horizontal, para que um card ocupe toda a largura da tela.

1. Abra o aplicativo
2. Clique em dicas

Espera-se que as opções de dicas fiquem alinhados. 

 - Modelo do Dispositivo: Asus Zenfone Pro Max M1.
 - Versão do Android: Versão 9.1.0.11
 - Versão do App: 3.0.0

**Comment by gabrieldouurado** [comment]
Estamos utilizando 2 colunas para o usuário conseguir enxergar o máximo de conteúdos sem precisar rolar o "scroll". Na ultima versão resolvemos o problema de possuir espaçamentos maiores entre os cards.
