### ISSUE TITLE
Aba de Notícias (atualizar twitter) 

### ISSUE THREAD

**Issue by juvenaljuniorrr** [proepidesenvolvimento/guardioes-app#124]
Na aba "Notícias" é preciso trocar o twitter pelo APPGUARDIÕES, onde são veiculados os boletim

1. Abrir o aplicativo
2. Clicar em notícia

**Comportamento Esperado**<br>
Espera-se que o twitter veiculado seja o @appguardioes e não o @guardioesunb 

Modelo do Dispositivo: Asus Zenfone Pro Max M1.
Versão do Android: Versão 9.1.0.11
Versão do App: 3.0.0

**Comment by gabrieldouurado** [comment]
Feature em desenvolvimento!

Issue #81
