### ISSUE TITLE
BUG (Foto de perfil)

### ISSUE THREAD

**Issue by juvenaljuniorrr** [proepidesenvolvimento/guardioes-app#125]
**Descrição**<br>
Tentei colocar a foto de perfil, mas quando saio da minha conta e faço o login novamente a foto não está mais lá, assim tenho que repetir o processo de adicionar a foto

**Comportamento Esperado**<br>
Espera-se que a foto de perfil que salva quando adicionada pela primeira vez

**Informações do Dispositivo:**
 - Modelo do Dispositivo: Iphone 7 
  Versão do iOS: 13.6
 - Vesão do App: 3.0.0

**Comment by gabrieldouurado** [comment]
Na verdade esse não é um bug, a foto de perfil fica salva apenas localmente, quanto o usuário realiza o logout, a informação do caminho da imagem também é apagado.
