### ISSUE TITLE
BUG Aviso na tela home descentralizado

### ISSUE THREAD

**Issue by Gabriella-Rossetti** [proepidesenvolvimento/guardioes-app#127]
**Descrição**<br>
Na tela home, o aviso: "Status nos últimos 7 dias" não está centralizado. Não aumento a letra do celular. 

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Abrir o App.
2. Clicar em Home

**Comportamento Esperado**<br>
Aviso centralizado

**Screenshots**<br>
![WhatsApp Image 2020-08-04 at 00 16 10](https://user-images.githubusercontent.com/69014630/89562896-0a698880-d7f1-11ea-8217-c10b13e7fa36.jpeg)

**Informações do Dispositivo:**
 - Modelo do Dispositivo: Samsung A50 Android 10
 - Vesão do App: 3.0.0

**Comment by gabrieldouurado** [comment]
Problema resolvido na v3.0.0 de produção.
