### ISSUE TITLE
BUG Gráfico pizza

### ISSUE THREAD

**Issue by Gabriella-Rossetti** [proepidesenvolvimento/guardioes-app#128]
**Descrição**<br>
O gráfico pizza não inclui os dias não informados

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Ir para diário
2. Ir para o gráfico pizza

**Comportamento Esperado**<br>
Encontrar, no gráfico, os números relativos aos reports em que se respondeu bem, mal e "não informado". Porém não informado aparece como número negativo e não aparece no gráfico. Seria interessante se todos fossem números positivos e constassem no gráfico pizza. 

**Screenshots**<br>
![WhatsApp Image 2020-08-06 at 14 33 53](https://user-images.githubusercontent.com/69014630/89563580-0427dc00-d7f2-11ea-836d-452ae967c1df.jpeg)

**Informações do Dispositivo:**
 - Modelo do Dispositivo: Samsung A50 Android 10
 - Vesão do App: 3.0.0

**Comment by gabrieldouurado** [comment]
Problema resolvido na v3.0.0 de produção.
