### ISSUE TITLE
BUG Diário não acompanha mudança de perfil

### ISSUE THREAD

**Issue by Gabriella-Rossetti** [proepidesenvolvimento/guardioes-app#129]
**Descrição**<br>
Quando mudo o perfil (saio do meu e vou para o do meu pai), o diário não acompanha essa mudança. 

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Clicar no perfil de outra pessoa
2. Clicar em diário
3. Ver o meu próprio diário

**Comportamento Esperado**<br>
Ver o diário da outra pessoa. No caso, do meu pai.

**Screenshots**<br>
![WhatsApp Image 2020-08-06 at 14 36 58](https://user-images.githubusercontent.com/69014630/89563949-a5af2d80-d7f2-11ea-9203-57713aed9fca.jpeg)

![WhatsApp Image 2020-08-06 at 14 33 53](https://user-images.githubusercontent.com/69014630/89563865-81ebe780-d7f2-11ea-9a42-27aa02ca142f.jpeg)

**Informações do Dispositivo:**
 - Modelo do Dispositivo: Samsung A50 Android 10
 - Vesão do App: 3.0.0

**Comment by Gabriella-Rossetti** [comment]
![WhatsApp Image 2020-08-06 at 14 42 48](https://user-images.githubusercontent.com/69014630/89564347-41409e00-d7f3-11ea-8a0a-7ff1b238329a.jpeg)

**Comment by gabrieldouurado** [comment]
Problema resolvido na v3.0.0 de produção!
