### ISSUE TITLE
Retirar "Interssexo”

### ISSUE THREAD

**Issue by juvenaljuniorrr** [proepidesenvolvimento/guardioes-app#131]
A Equipe de Comunicação fez uma pesquisa com relação as identidades de gênero do aplicativo e percebemos que "Intersexo" não está adequado corretamente. O termo interssexual é relacionado ao sexo biológico.

Nesse sentido, essa issue é pra pedir que seja retirado "Intersexual" das opções de Gênero na edição de perfil.

![6800CE83-DC62-484B-B5C4-D9B415E01854](https://user-images.githubusercontent.com/68300937/89828299-41140b80-db2f-11ea-957c-9016661001b3.png)

**Comment by alvesitalo** [comment]
Interssexo foi retirado na branch **development**.
