### ISSUE TITLE
Inserção de texto e Organização da aba DICAS 

### ISSUE THREAD

**Issue by joaovitor26** [proepidesenvolvimento/guardioes-app#133]
**Descrição**<br>
Atualização da aba de dicas→ Acrescentar uma dica chamada: “Em caso de suspeita de COVID-19, o que eu devo fazer e que serviços devo procurar?”

Inserir o seguinte texto nesta dica:

Se estiver doente, com sintomas compatíveis com a COVID-19, tais como febre, tosse, dor de garganta e/ou coriza, com ou sem falta de ar:

- Procure imediatamente os postos de triagem nas Unidades Básicas de Saúde e UPAS ou em outras unidades de saúde.
- Após encaminhamento dos profissionais da unidade de saúde consulte-se com o médico.
- Uma vez diagnosticado pelo médico, receba as orientações e prescrição dos medicamentos que você deverá usar.
- Não se esqueça de evitar contato físico com outras pessoas, incluindo os familiares, principalmente, idosos e doentes crônicos.
- Sempre utilize máscara.
- Separe toalhas, talheres e copos somente para o seu uso.
- O lixo produzido pelo indivíduo com suspeita ou já diagnosticado deverá ser separado e descartado.
- Evite compartilhamento de sofás e cadeiras e limpe rotineiramente com álcool 70% ou água sanitária os mesmos e as maçanetas.
- Caso o indivíduo não more sozinho, é importante que os outros moradores mantenham distância de 1 metro e durmam em cômodo diferente do infectado.

Referência: https://coronavirus.saude.gov.br/sobre-a-doenca#se-eu-ficar-doente

Link para o documento com o texto acima: https://docs.google.com/document/d/1iAW7HRA5heo3Q-y9-Pzti10OiIxQk8qmqnVR48-bpY4/edit

-> Organização da aba "dicas" em ordem de prioridade: I. Aba "Dicas":
- A primeira deve ser aquela da homepage do MS "Em caso de suspeita de COVID-19, o que eu devo fazer?"
- Segunda: "Em caso de suspeita de COVID-19, que serviço eu devo procurar?"
- Terceira: O uso das máscaras de tecido 
- Quarta: Seu guia básico sobre COVID-19 
- Quinta: Prevenção 
- Sexta: Links e telefones úteis 
- Sétima: Produtividade na quarentena 
- Oitava: Vacinas durante a epidemia 
- Nona: Saúde do viajante

-> Adicionar uma dica sobre: Apoio Psicológico oferecido pela UnB durante a pandemia.

Talvez você não saiba, mas a UnB oferece muitos serviços de Apoio Psicológico, principalmente na pandemia. Alguns deles são:
Atendimento Psicológico/Psicossocial On-line, em grupo ou individual: é definido como uma escuta ativa e gratuita, sobre o contexto de pandemia e suas consequências para a saúde mental dos indivíduos.

FalArte: espaço de fala aberto que busca acolher os envolvidos.

Diztanto: escuta em tempos de pandemia: tem o objetivo de promover um espaço de escuta, troca de conhecimentos e experiências. 

Psicoterapia de Grupo em Psicodrama: programa em parceria com a Associação Brasiliense de Psicodrama, é um grupo que visa o compartilhamento de estratégias em relação à saúde mental na pandemia.

Do Giz à Palavra: espaço online de encontro entre professores para troca de experiências nesse momento de isolamento social.

Essas são apenas algumas alternativas que a Universidade de Brasília oferece, para saber mais é só entrar no link abaixo: http://www.dac.unb.br/atividades-dasu/apoio-psicologico
Referência: http://www.dac.unb.br/atividades-dasu/apoio-psicologico

-> Adicionar uma dica sobre: Promoção da Saúde na UnB.

Alternativas de Promoção da Saúde estão sendo apresentadas e executadas pela UnB, essencial para você, que precisa participar de uma atividade para desestressar.

=
Práticas de Mindfulness: através de encontros online, fornecem práticas multimodais que incluem relaxamento, centramento e psicoeducação; por meio de visualização guiada, consciência da respiração e alongamentos.

Bate-papo Literário: tem o objetivo de estimular a leitura prazerosa e o contato e a aproximação, em tempos de distanciamento social, por meio da literatura.

Roda de Conversa "Clássicos Literários": os livros serão decididos de forma conjunta e tem encontros semanais, ótima oportunidade para quem ama ler.

Tem muito mais, se você se interessou acesse o link:  http://www.dac.unb.br/atividades-dasu/promocao-da-saude

Referência: http://www.dac.unb.br/atividades-dasu/promocao-da-saude

-> Adicionar uma dica sobre: Como se manter atualizado: conheça a UnBTV.

Como se manter atualizado na pandemia, por um canal confiável, é um grande desafio. Por isso, apresento a vocês a UnbTV: um canal no youtube com vídeos de temáticas variadas, incluindo: vacinas, cultura, conversa com especialistas sobre assuntos de pesquisa e muito mais.

Para acessar, entre no link: https://www.youtube.com/user/unbtv/videos
Referência: https://www.youtube.com/user/unbtv/videos

->Sugestão: Arquivar a dica de: saúde do viajante

**Comment by gabrieldouurado** [comment]
A organização dos conteúdos está sendo feita de acordo com o tamanho do título, assim garantimos que os espações entre os cards fiquem homogêneos.

**Comment by gabrieldouurado** [comment]
@joaovitor26 O conteúdo já foi adicionado?
