### ISSUE TITLE
Alteração de Texto do alerta de suspeita de COVID

### ISSUE THREAD

**Issue by joaovitor26** [proepidesenvolvimento/guardioes-app#135]
A equipe de comunicação, sob demanda do Professor Iturri pede que, no caso de usuários que se sentem "mal" e o algoritmo leva à suspeita de covid-19, o texto atual precisa ser alterado para o seguinte texto:

Baseado nos seus sintomas, você se enquadra como um compatível com a COVID-19: Procure imediatamente os postos de triagem nas Unidades Básicas de Saúde / UPAS ou outras unidades de saúde.
Utilize máscara o tempo todo; a pessoa que lhe acompanha também.

Maiores informações:
https://coronavirus.saude.gov.br/o-que-fazer
https://coronavirus.saude.gov.br/sobre-a-doenca#se-eu-ficar-doente

Mensagem em inglês

Based on your symptoms, you fit as compatible with COVID-19: Immediately seek for triage posts at Basic Health Units / UPAS or other health units.
wear a mask at all time as well as the person who accompanies you.

More information:
https://coronavirus.saude.gov.br/o-que-fazer
https://coronavirus.saude.gov.br/sobre-a-doenca#se-eu-ficar-doente

Mensagem em espanhol

Sus síntomas son compatibles con la COVID -19: busque inmediatamente puestos de triaje en las Unidades Básicas de Salud / UPAS y otros servicios de salud. Utilize una mascarilla en todo momento, así como la persona que  lo acompaña.  
Más informaciones:
https://coronavirus.saude.gov.br/o-que-fazer
https://coronavirus.saude.gov.br/sobre-a-doenca#se-eu-ficar-doente

Tal mudança se faz necessária, pois o Ministério da Saúde atualizou o texto que deve ser encaminhado a pessoas que apresentam sintomas de COVID-19. A referência pode ser encontrada nos links acima. 
Hoje, o texto aparece da seguinte forma: 

Atenção
Baseado nos seus sintomas, você se enquadra na definição de casos suspeito de síndrome gripal. Caso a febre persista e você esteja com dificuldades para respirar, procure um atendimento médico. Caso contrário, a não ser que seu quadro mude, não é recomendado que você procure atendimento médico agora. Continue usando o app para monitorar seus sintomas e mantenha a precaução e a etiqueta respiratória e, se puder, fique em quarentena por pelo menos 14 dias.

Fonte: Ministério da Saúde

**Comment by tsrrodrigues** [comment]
João, você pode nos enviar, por aqui mesmo, a tradução desse texto para inglês e espanhol, por favor?

**Comment by joaovitor26** [comment]
Claro, enviarei assim que estiver pronto.

**Comment by gabrieldouurado** [comment]
@tsrrodrigues alterações foi realizada?

**Comment by tsrrodrigues** [comment]
@gabrieldouurado ainda não foi enviado a tradução do texto.

**Comment by tsrrodrigues** [comment]
O PR #146 fecha essa issue. A mensagem foi mudada no servidor e o usuário ja a recebe. O link foi adidionado ao fim da mensagem. O redirecionamento do usuário quando clicado em "Mais Informações" foi mudado no PR citado, mas só irá mudar para o usuário quando for submetido uma atualização do app na loja e o mesmo atualizar em seu celular. Após isso ser feito, a fonte com o link pode ser removida da mensagem.
