### ISSUE TITLE
Erro no acesso ao aplicativo 

### ISSUE THREAD

**Issue by joaovitor26** [proepidesenvolvimento/guardioes-app#141]
**Descrição**<br>
Na manhã de 14/08, o usuário foi deslogado do aplicativo. Após a tentativa de realizar login, uma mensagem informando "Ocorreu um erro, tente novamente depois." aparece.

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Vá para Guardiões da Saúde
2. Clique em login
3. Insira os dados de login
4. Visualize a mensagem

**Screenshots**<br>
Pelo menos uma screenshot do bug.

**Informações do Dispositivo:**
 - Modelo do Dispositivo: Asus Zenfone Pro Max M1 
 - Versão do OS: Android Versão 9.1.0.11
 - Versão do App: última arquivo apk enviado antes da release.

**Comment by gabrieldouurado** [comment]
O erro ocorreu devido a uma queda no servidor! 

Problema já resolvido!
