### ISSUE TITLE
Dados de matrícula e instituição desapareceram 

### ISSUE THREAD

**Issue by Gabriella-Rossetti** [proepidesenvolvimento/guardioes-app#143]
**Descrição**<br>
Com a nova atualização, diversos usuários vem relatando que os dados de matrícula e instituição sumiram de seu perfil. 

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Ir em editar perfil
2. Ver o erro (instituição e matrícula somem)

**Comportamento Esperado**<br>
É esperado que tanto matrícula quanto instituição não sumam. 

**Screenshots**<br>
Pelo menos uma screenshot do bug.
![WhatsApp Image 2020-08-19 at 08 56 14](https://user-images.githubusercontent.com/69014630/90644890-accf3600-e20b-11ea-8c76-5d74e539d7b4.jpeg)

**Informações do Dispositivo:**
 - Modelo do Dispositivo: Samsung A50 Android 10
 - Vesão do App: 3.0.0

**Comment by gabrieldouurado** [comment]
Isso ocorreu devido a atualização no sistema de seleção de instituição. Usuários que atualizaram o cadastro e selecionaram um departamento, automaticamente passaram a pertencer a faculdade do departamento escolhido. Usuários que não atualizaram o cadastro, foram migrados para o novo sistema, continuaram na mesma faculdade.

Usuários que selecionaram no "Universidade de Brasília - Darcy Ribeiro", nas primeiras semanas de uso do app, precisam atualizar o seu cadastro manualmente.
