### ISSUE TITLE
 Lista de Departamentos confusa

### ISSUE THREAD

**Issue by juvenaljuniorrr** [proepidesenvolvimento/guardioes-app#144]
Muitos usuários relataram que não sabem o que adicionar em "departamentos" tendo em vista que "na aba de selecionar o curso, apenas me permite escolher os cursos de Engenharias **específicas**, não o tronco comum" (relato de um usuário)

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Abra o aplicativo
2. Editar Perfil

**Comportamento Esperado**<br>
Espera-se que as faculdades tenham apenas as opções principais da unidades acadêmicas (http://www.saa.unb.br/gradua/149-unidades-academicas), tendo em vista que os departamentos específicos no âmbito da graduação servem apenas para a escolha de disciplinas.

**Comment by gabrieldouurado** [comment]
Issue resolvida. Atualmente o ultimo nível de filtragem é faculdade!
