### ISSUE TITLE
Analisar se existe algum problema (O app pula o dia da marcação)

### ISSUE THREAD

**Issue by juvenaljuniorrr** [proepidesenvolvimento/guardioes-app#145]
**Descrição**<br>
A usuária relatou que "em alguns momentos o app tá pulando as marcações que faço". Perguntei pra ela se aparecia a mensagem de envio, ela informou que sim. Pedi as informações do celular dela e android para esse problema ser analisado. 

 
**Screenshots**<br>
Ela disse que perdeu os dias "os dias 4, 5, 7, 9 e 13!"
![WhatsApp Image 2020-08-19 at 16 25 55](https://user-images.githubusercontent.com/68300937/90680881-ea968380-e238-11ea-9bb6-ca12f13a04fb.jpeg)

**Informações do Dispositivo:**
 - Modelo do Dispositivo: galaxy j7 prime
 - Versão do Android: 8.1.0
 - Vesão do App: última da google play

**Comment by gabrieldouurado** [comment]
Os relatos funcionam da seguinte forma:

App (request) -> API(Processa a request e retorna 200 [ok] ou algum outro erro) ->  App: Caso retorne 200 (Retorna ao usuário que o relato foi feito), caso retorne algum erro (Retorna o erro para o usuário -  relato não é feito).

O diário funciona da seguinte forma:

App (resquet com id do user) -> API (Processa a request) -> App (Recebe todos os relatos daquele usuário. No caso de erro ele o usuário não receberia nenhum relato)

Observando o funcionamento, se a mensagem de confirmação apareceu, confirmando que o relato foi feito, o relato teria que aparecer no diário. Caso ocorresse algum tipo de erro no diário, o usuário não receberia nenhum dado, nem a porcentagem não ficaria funcionando.

Essa lógica já foi revisada e não foi encontrado nenhum erro nela. Diante disso estarei fechando essa issue.
