### ISSUE TITLE
Aceite das politicas de privacidade.

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-app#149]
**Descrição **<br>
Gerar um mecanismo para o usuário aceitar as novas politicas de privacidade.

**Critérios de aceite**
- [x] Verificar se o usuário está de acordo com a ultima política de privacidade.
- [x] Sair do aplicativo se o usuário não aceitar;

**Comment by alvesitalo** [comment]
Concluído quando o pull request #152 for aprovado e mergido.
