### ISSUE TITLE
Métricas de notificação 

### ISSUE THREAD

**Issue by joaovitor26** [proepidesenvolvimento/guardioes-app#160]
Como parte do grupo de comunicação do Guardiões, visando cumprir com os combinados acerca do envio de notificações personalizadas aos usuários, peço que as seguintes tags sejam "codadas" na API. Abaixo, será descrita a TAG, a métrica desejável e os resultados esperados a partir de sua implementação.

TAG 1: divisão de usuários por instituição ou grupos. 
Métrica: UnB; IFB; Sec. de educação; demais intituições
Ex: opção de envio de notificação apenas para o grupo UnB ou grupo IFB ou usuário que não pertença a nenhum grupo. 
Espera-se que atendamos as demandas específicas de cada grupo. 

TAG 2: Região Administrativa
Métrica: divisão por RAs: Taguatinga, Ceilândia, Samambaia e demais RAs. 
Ex: Enviar notificação apenas para usuários residentes de Taguatinga 
Espera-se integrar essa opção aos dados do Boletim, a fim de avisar usuários sobre surtos em sua RA. 

TAG 3: usuários com cadastro incompleto (hoje, soma-se mais de 5.000 usuários).
Métrica: selecionar um dado de registro sobre instituição UnB específico como filtro para encaminhar a notificação- Faculdade; Instituição; Matrícula;
Ex: Eu, João, esqueci de inserir a matrícula no cadastro. Lara, minha amiga, esqueceu de inserir a instituição, mas inseriu a matrícula. Será possível selecionar a variável de cadastro incompleto e enviar a notificação.
Espera-se evitar que usuários, após o cumprimento dos requisitos, fiquem sem créditos. 

TAG 4: usuários com baixa adesão ou engajamento 
Métrica/condição: dentro do intervalo de 3 dias o usuário tiver engajamento igual ou superior a 2. 
Exemplo: Eu, João, lembrei de reportar o guardiões apenas 1 vez, nos último 3 dias. Poderei receber uma notificação me alertando sobre meu engajamento.
Espera-se que o engajamento dos usuários seja acima dos 65% até o fim de agosto. 

TAG 5:  usuários sintomáticos 
Métrica: Total de dias registrando "mal" igual a 2.
Ex: Eu, João, marquei sintomas que me colocam na condição de suspeita de COVID. Poderei receber uma notificação reforçando a indicação para que uma unidade de saúde seja buscada. 
Espera-se que o app possa cumprir o propósito de ser uma resposta à COVID-19. 

TAG 6: usuário sintomático que deixou de reportar
Métrica: usuário que marcou "mal" e nos dois dias seguintes deixou de registrar o estado de saúde.
Ex: Eu, joão, registrei antes de ontem "mal" no Guardiões e após dois dias sem registrar, recebi uma notificação me lembrando de relatar o estado de saúde. 
Espera-se que possamos incentivar a Vigilância Participativa por parte dos usuários que apresentam sintomas semelhantes ao de COVID, a fim de que os demais usuários tenham uma resposta contínua acerca da "saúde do bairro".

**Comment by gabrieldouurado** [comment]
TAG: “group”
Retorna a instituição do usuário. Se o usuário não possuir group essa variável não será mostrada nas tags dele.

TAG: “city”
Retorna a cidade (RA, para Brasilia) que o usuário selecionou no ato do cadastro.

TAG:  “school_unit_id”
Retorna o ID da instituição do modelo antigo.
Motivo: Alcançar usuários que estão no modelo antigo de instituição. App 8.5k somente da UnB

TAG: Score 
Dias consecutivos que o usuário reportou
