### ISSUE TITLE
Acentuação nos cards da gamificação

### ISSUE THREAD

**Issue by Gabriella-Rossetti** [proepidesenvolvimento/guardioes-app#169]
**Descrição**<br>
As palavras do card não estão acentuadas. 

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Abrir o app
2. Reportar estado de saúde
3. Ver o card

**Comportamento Esperado**<br>
Card com as palavras acentuadas 

**Screenshots**<br>
![WhatsApp Image 2020-10-13 at 11 08 54](https://user-images.githubusercontent.com/69014630/95872095-d062b880-0d44-11eb-93ce-15ed28576360.jpeg)
![WhatsApp Image 2020-10-13 at 11 08 54 (1)](https://user-images.githubusercontent.com/69014630/95872099-d22c7c00-0d44-11eb-9eb4-d3e7e9ae1a11.jpeg)

**Informações do Dispositivo:**
 - Modelo do Dispositivo: Samsung A50
 - Versão do App:

**Comment by Gabriella-Rossetti** [comment]
Versão do app: 3.1.0

**Comment by tsrrodrigues** [comment]
Olá Gabriella. Estamos ciente deste problema. Colocamos as mensagens sem caracteres especiais para que estivessem disponibilizadas o mais rápido possível. Mas iremos trabalhar nisso quando possível. Obrigado pela colaboração.

**Comment by tsrrodrigues** [comment]
As mensagens foram atualizadas no servidos. Tudo já deve estar com os caracteres especiais. Fechando a issue.
