### ISSUE TITLE
Ordenação e organização da Aba dicas de Saúde

### ISSUE THREAD

**Issue by gabrieldouurado** [ProEpiDesenvolvimento/guardioes-app#173]
**Descrição**<br>
Ordenar a aba de Dicas de Saúde de modo que os cards mais recentes fiquem na parte superior.

Organizar os cards de modo que o espaçamento entre eles fique homogêneo. Considerar o tamanho do título.

**Critérios de aceite**
- [x] Aba de Dicas de Saúde ordenada do mais recente para o mais antigo;
- [x] Cards com espaçamentos iguais independente do tamanho do titulo;

**Comment by gabiMSilva** [comment]
@gabrieldouurado Tenho algumas dúvidas:

1 - Atualmente ele é ordenado pelo título de menor tamanho para o maior, é pra remover completamente essa ordenação e deixar apenas pelo mais recente?

2 - Esse espaçamento seria o que está em vermelho?

![Screenshot_1603836379](https://user-images.githubusercontent.com/36926637/97367508-01380700-1888-11eb-9954-7473c0297801.png)

**Comment by gabrieldouurado** [comment]
Olá @gabiMSilva 

Respondendo as perguntas:
1. Isso ordenado apenas pelo mais recente. Porem títulos com tamanhos diferentes geram cards com tamanhos diferentes, isso gera um espaçamento heterogêneo.

2. O espaçamento precisa ser esse em vermelho:
![Captura de Tela 2020-10-28 às 13 42 22](https://user-images.githubusercontent.com/41026043/97468924-925cbb80-1924-11eb-8700-4697a74ac455.png)

3. Podemos retornar o created_at, updated_at na resposta.

**Comment by gabiMSilva** [comment]
> Olá @gabiMSilva
> 
> Respondendo as perguntas:
> 
> 1. Isso ordenado apenas pelo mais recente. Porem títulos com tamanhos diferentes geram cards com tamanhos diferentes, isso gera um espaçamento heterogêneo.
> 2. O espaçamento precisa ser esse em vermelho:
>    ![Captura de Tela 2020-10-28 às 13 42 22](https://user-images.githubusercontent.com/41026043/97468924-925cbb80-1924-11eb-8700-4697a74ac455.png)
> 3. Podemos retornar o created_at, updated_at na resposta.

Obrigada pela resposta!

Vou dar uma olhada no backend e ser for fácil já adiciono esses campos na resposta e corrijo no PR. Caso não consiga falo aqui com vocês hehe

**Comment by gabiMSilva** [comment]
@gabrieldouurado Obrigada pelas respostas!
Aguardo a adição desses atributos então para corrigir o PR #175

**Comment by gabrieldouurado** [comment]
@gabiMSilva Feito. PR https://github.com/proepidesenvolvimento/guardioes-api/pull/197
