### ISSUE TITLE
Refatorar a maneira que usuários se inscrevem nos grupos.

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-app#204]
**Descrição**<br>
Retirar cadastro de instituição da tela de cadastro e criar um botão dedicado a isso no editar perfil.

**Critérios de aceitação**
- [x] O usuário clicar em um botão na tela de editar perfil para que ele tenha acesso as informações de sua instituições. 
- [x] Remover da tela de cadastro a escolha da instituição
- [x] O usuário precisa conseguir desvincular o seu perfil com o de uma instituição.
- [x] Ao desvincular é necessário sejam apagadas as informações referentes a Vigilancia Ativa.

**Comment by valessiobrito** [comment]
Pessoal, parabéns pela iniciativa e aplicativos de vocês.  No caso de "instituições" poderiam deixar mais "genérico" para qualquer tipo de instituição/empresa/organização?

Sendo uma organização "mobilizadora" no uso do app;  Gostaria de cadastrar uma empresa/grupo cujo oferece outras formas de "benefícios" para quem usa.    Exemplo:  uma pizzaria, poderia dar uma pizza ao final do mês para quem cumpre X dias de uso.

**Comment by gabrieldouurado** [comment]
@valessiobrito Muito obrigado! Fico muito feliz com seu comentário.

De fato, atualmente a "instituição" é apenas um termo para os grupos, é possível que qualquer empresa ou organização faça parte.

Mais interessante que as estratégias de gamification, é que quando os usuários são inscritos em um grupo, conseguimos fazer o a Vigilância em Saúde, que é observar as informações coletadas e identificar possíveis surtos, agravos ou doenças,  daquele grupo específico. Um grande exemplo disso é a Universidade de Brasília que faz uso da aplicação para cuidar da saúde de seus alunos e servidores.
