### ISSUE TITLE
Realizar o tratamento para municípios que não possuem um grupo cadastrado.

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-app#210]
**Descrição**<br>
Realizar o tratamento para municípios que não possuem um grupo cadastrado no momento da seleção de um grupo por um usuário.

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Abrir a página de Cadastro no Guardiões da Saúde.
2. Selecionar que faz parte de uma instituição.
3. Selecionar um município que não possui instituições (Grupos) Ex. Brasil -> Goiás -> Goiânia.

**Comportamento Esperado**
Que apareça uma mensagem para o usuário que aquele Município não possui Grupos cadastrados.

**Critérios de Aceitação**
- [x] Mensagem de que não existe grupo naquele município;
- [x] O fato de não existir grupo, não impedir do usuário terminar de se cadastrar. [Valido somente se a lógica de edição e cadastro de instituição ainda permanecer nas páginas de edição e cadastro de usuário, respectivamente]

**Screenshots**
![Captura de Tela 2021-03-16 às 17.15.47.png](https://images.zenhubusercontent.com/5d7eeb7d9e6efa0001036ae3/1484f9b5-494d-494c-b8d2-b9d161cc5fb0)

**Comment by valessiobrito** [comment]
Cheguei nessa tela;  Não seria o caso de ter o botão "cadastrar organização" e isso vira um item a ser moderado (aprovar ou não o cadastro)  no sistema?
