### ISSUE TITLE
Problema com as datas

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-app#215]
**Descrição**
Verificar o que pode está acontecendo com os DateSelector.

![Captura de Tela 2021-03-18 às 15.46.46.png](https://images.zenhubusercontent.com/5d7eeb7d9e6efa0001036ae3/ea0f51fa-3df2-4ea5-ac95-4b67df5f634f)

**Comment by alvesitalo** [comment]
O erro é causado devido a versão atual mais antiga React Native. Na versão mais atual o problema não ocorre: 
![Simulator Screen Shot - iPhone 11 - 2021-04-14 at 18 43 09](https://user-images.githubusercontent.com/35741521/114784374-8b4e2c00-9d51-11eb-88c1-d5b7b07c72c4.png)
