### ISSUE TITLE
Alerta para Fazer parte da Vigilância Ativa.

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-app#233]
**Descrição**

Quando o report de um usuário der match com alguma sindrome, gerar um alerta convidando-o a fazer parte do programa de Vigilância Ativa. O intuito é converter esses usuários para que os seus reports passem a ser "vigiados".

Requisitos
 - O usuário não pode fazer parte da Vigilância Ativa(`is_vigilance: false`);
 - O usuário precisa pertencer a um grupo;
 - Esse grupo, precisa fornecer a Vigilância Ativa;

Conversar com a Equipe de Comunicação a respeito a mensagem que irá aparecer no alerta.

Validar os fluxos de report sintomático:
1 - Mensagem de recomendação;
2 - (NOVO) Alerta para fazer parte da Vigilância
3 - Card para ser compartilhado.

**Critérios de Aceitação**
- [ ] A mensagem ser renderizada para o usuário que preencher os requisitos;
- [ ] Usuário ser redirecionado para página da Vigilancia ativa;

**Comment by gabrieldouurado** [comment]
A issue não atendeu a esses requisitos:

- O usuário precisa pertencer a um grupo;
- Esse grupo, precisa fornecer a Vigilância Ativa;

**Comment by gabrieldouurado** [comment]
O item 2 não foi solucionado. 

Utilizar o setShowAlert.

**Comment by gabrieldouurado** [comment]
O botão de Vigilância Ativa parou de ser renderizado, mesmo quando o usuário cumpre os pré-requisitos para ele aparecer.

A mensagem para participar da Vigilância Ativa também parou de aparecer.

**Comment by jps12** [comment]
Foi alterada a lógica para guardar o valor do email da vigilância ativa. Não consegui reproduzir o bug, mas imagino que essas alterações vão dminuir a probabilidade de erros
