### ISSUE TITLE
ID-6 - Adicionar terceira dose da vacina contra COVID

### ISSUE THREAD

**Issue by alvesitalo** [ProEpiDesenvolvimento/guardioes-app#267]
**Descrição**<br>
Deverá ser refatorada a página de vacinação do aplicativo. O usuário deverá ter o seguinte fluxo:
- Na página de editar perfil ele clica no campo "Possui dados da vacina" e é redirecionado para a página de vacinação.
- Ao entrar na página o usuário deverá ver uma lista de doses que ele tomou.
- Ele poderá clicar em botão para adicionar mais uma dose. Ao apertar esse botão deverá aparecer um modal.  

Também é necessário corrigir o bug que faz o seletor de data voltar 1 dia atrás após salvar os dados de vacinação (pode envolver a API).

**Tarefas:**

- [ ] Os dados introduzidos no cadastro de uma nova dose deve ser os mesmo para preencher a model dose a ser criada na issue

**Comment by robsonramon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Guardies-da-Sade-5ee7aefe790e2700257237fe/issues/ProEpiDesenvolvimento/guardioes-app/267?planning-poker) with ZenHub @alvesitalo @AnaBeatrizPontes @clarice42 @EduardoMdR @jps12

**Comment by clarice42** [comment]
@alvesitalo no app atualmente existe uma validação que só permite que o usuário adicione a segunda dose depois de adicionar a primeira. Como agora essa tela vai ser uma lista de doses já tomadas, faz sentido manter isso? Ou o usuário pode adicionar as doses na ordem que ele quiser?

**Comment by alvesitalo** [comment]
@clarice42 Sim, se o id da vacina já existir, a lógica é que se incremente o valor de dose. Por exemplo, se já existir a 1ª e 2ª dose com a vacina de id: 44, a próxima dose deve ser a 3ª.
