### ISSUE TITLE
Limitar a quantidade de reports por dia - API

### ISSUE THREAD

**Issue by RochaCarla** [proepidesenvolvimento/guardioes-app#31]
Limitar a quantidade de reports por dia para 2 (1 bom e 1 ruim por dia)

- [x] verificar se ja tem o limite de reports diários e retornar json de resposta

# Critério de Aceitação

- [ ] O usuário não consegue reportar o mesmo sintoma no mesmo dia

**Comment by tsrrodrigues** [comment]
Não existia um limite para reports diários. Um [Pull Request #62](https://github.com/proepidesenvolvimento/guardioes-api/pull/62) foi criado para resolver essa issue.

**Comment by tsrrodrigues** [comment]
[Pull Request #62](https://github.com/proepidesenvolvimento/guardioes-api/pull/62) aprovado. Fechando a issue.
