### ISSUE TITLE
Cadastrar novos conteudos no servidor

### ISSUE THREAD

**Issue by RochaCarla** [proepidesenvolvimento/guardioes-app#34]
Cadastrar novos conteúdos sobre as dicas

- [x] Subir os documentos gerados pela equipe de comunicação no servidos

# Critério de aceitação
 

- [ ] Dicas atualizada com novos documentos

**Comment by ViniciusPuerto** [comment]
Para criar um novo conteúdo basta fazer a senguinte request

```
curl --location --request POST 'localhost:3001/contents/' \
--header 'Authorization: token aqui' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"contents": 
		{
			"title": "Teste Content",
			"body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam convallis posuere libero ut dapibus. Quisque auctor vehicula dui quis pellentesque. Maecenas egestas non erat nec placerat. Maecenas sit amet porttitor lorem, eu tempus lorem. Duis interdum ultricies mattis. Duis nunc erat, accumsan et felis sed, faucibus lobortis risus. Vestibulum tristique nisl in magna convallis, in porttitor lectus condimentum. Sed eu massa elit. Sed id elementum justo.",
			"content_type": "text",
			"app_id": 1
		}
}'
```

**Comment by gabrieldouurado** [comment]
O JSON para a criação de de um novo Conteúdo:

{
	"content": 
		{
			"title": "Título do Conteúdo",
			"body": "Texto do Conteúdo",
			"content_type": "text",
			"source_link": "Link da fonte da informação",
			"app_id": id ao qual pertence o conteúdo
		}
}

**Comment by tsrrodrigues** [comment]
**Updates**
**Saúde do Viajante**
Segundo orientações do professor Iturri. O conteúdo de _Saúde do Viajante_ foi substituído pela informação disponibilizada no chat TeleSUS na página inicial do website do Ministério da Saúde. Para obter as informações entre no chat e siga os passos: Estou com duvidas -> Informações para viajantes -> E viagens futuras? -> Recomendações. Assim irá ser obtido todo o conteúdo de _Saúde dos Viajante_ .
**Telefones Úteis**
O título deste conteúdo foi alterado para _Links e Telefones Úteis_ devido ao alerta sobre o chat do TeleSUS.
O conteúdo de _Telefones Úteis_ foi atualizado contendo agora os números do disque sáude(136) e alertando sobre o chat TeleSUS do site do Ministério da Saúde.
**Prevenção**
Não foi orientada nenhuma mudança no conteúdo de _Prevenção_.
**Doenças Imunopreveníveis**
Foi orientada mudanças no conteúdo, porém ainda está no aguardo desse novo conteúdo.

**Comment by tsrrodrigues** [comment]
**Updates**<br>
**Doenças Imunopreveníveis**
_Doenças Imunopreveníveis_ foi removido segundo orientações do professor Iturri. Quando for enviado, adicionarei o novo conteúdo. Por enquanto irei fechar a issue.
