### ISSUE TITLE
Problema para gerar relatório

### ISSUE THREAD

**Issue by guilacerda** [proepidesenvolvimento/guardioes-app#36]
**Descrição**<br>
O usuário gds-convidado no Kibana não está conseguindo gerar o relatório.

**Tarefas**
- [ ] Criar uma permissão para usuários convidados conseguirem fazer o download do csv de cada visualização.

**Critérios de aceitação**

- [ ] Usuário convidado consegue fazer o download dos relatórios

**Comment by RenatoBrittoAraujo** [comment]
Movido para o repositorio web
