### ISSUE TITLE
Caching de ending points mais importantes

### ISSUE THREAD

**Issue by RochaCarla** [proepidesenvolvimento/guardioes-app#37]
Fazer o caching das rotas que são mais usadas no aplicativo 

- [x] Identificar as rotas mais usadas

- [x] Fazer o caching no serializer da rota

# Critério de aceitação

- [x] Dados cacheados

**Comment by ViniciusPuerto** [comment]
Uma sugestão de como pode ser feito no [link](https://hugotunius.se/2015/01/21/active-model-serializer-caching.html)

**Comment by RenatoBrittoAraujo** [comment]
Para poder avaliar o impacto da mudança, irei anotar nessa issue os ganhos em performance.

Abaixo estão testes de tempo de request antes de começar a fazer qualquer tipo de caching em máquina local.

As medidas foram feitas com o programa a seguir:

```
echo "URL: "
read url
echo "Filename: "
read filename
touch "test_$filename.txt"
echo "Number of requests: "
read num_req
for i in `seq 1 $num_req`
do
        /usr/bin/time --output test_$filename.txt --append -f "%e" curl -XGET $url
        clear
        echo "Try $i of $num_req"
done
echo "Done"
num_req=$num_req.0
var=$(awk '{s+=$1} END {print s}' test_$filename.txt)
calc(){ awk "BEGIN { print "$*" }"; } 
calc $var/$num_req
```

Resultados:

|Número de itens|Média de tempo para 10 queries|
|-|-|
|1000 | 1437 ms |
|10000 | 5175 ms |
|50000 | 16529 ms |

**Comment by RenatoBrittoAraujo** [comment]
Na branch [feature/caching](https://github.com/proepidesenvolvimento/guardioes-api/tree/feature/caching) da api se encontra o código do sistema de caching.

O caching funciona assim: a cada 15 minutos, um novo objeto de cache é criado e o server retorna esse objeto. O objeto é criado a partir da primeira request feita sem cache, e a partir do momento que ele é criado, continua servindo os usuários. Isso singnifica que algum usuário a cada 15 minutos vai fazer um query demorando em torno de 400-1000 ms, em troca disso as queries dos usuários subsequentes são de ~50 ms. A média de tempo por request caiu drasticamente.

| Numero de itens | Média de tempo para 10 queries |
| - | - |
| 1000 | 62 ms |
| 10000 | 251 ms |
| 50000 | 583 ms |

**Comment by RenatoBrittoAraujo** [comment]
A redução de tempo nas queries de pinos do mapa ficou em torno de 33% para o usuário final, levando a média de 4558 ms para 3051 ms. 

Desse tempo, 630 ms é o tempo minimo que qualquer querie, até as mais simples. Como o arquivo JSON fica em torno de 500 kB e a conexão que estou é de 1 mB/s, temos mais ~500 ms de download. 

Dessa forma, no final podemos comparar de forma mais direta o caching amortizado versus sem cache: 3428 ms antes versus 1921 agora, uma redução de 56%.
