### ISSUE TITLE
Melhorar a pagina inicial do Guardiões

### ISSUE THREAD

**Issue by RochaCarla** [proepidesenvolvimento/guardioes-app#44]
Melhorar a página "Home"do guardiões

- [ ] tem um logo no guardiões no topo da página e depois tem uma mensagem "Agora vc eh um guardião da saude"

- [ ] quando a tela rotacional, perde a estrutura do texto

- [ ] experiencia do usuario na principal pagina do app eh ruim

**Comment by RochaCarla** [comment]
![photo_2020-06-19_08-58-42](https://user-images.githubusercontent.com/5897389/85130432-4f1e6d80-b20b-11ea-9c0f-50e0c6f4e1bd.jpg)
![photo_2020-06-19_08-59-55](https://user-images.githubusercontent.com/5897389/85130437-50e83100-b20b-11ea-9b4d-063c3b5b90d2.jpg)

**Comment by alvesitalo** [comment]
Em progresso na issue #50.
