### ISSUE TITLE
Compartilhar mensagem whatsapp

### ISSUE THREAD

**Issue by RochaCarla** [proepidesenvolvimento/guardioes-app#49]
Funcionalidade para compartilhamento de texto a partir dos guardiões

Tarefas

- [x] criação do texto de compartilhamento

- [x] Link do feedback

- [x] Verificar se o report é linkado com sindrome do Covid

- [x] Dar opção de compartilhamento pelo wpp

- [x] Consultar Jonas para coletar informações

Critérios de Aceitação

- [x] Poder compartilhar report caso seja linkado com sindrome

**Comment by tsrrodrigues** [comment]
## Update
Irei refatorar a issue e o pull request para compartilhar um cartão em vez de uma mensagem de texto.
