### ISSUE TITLE
Melhorias graduais no design

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-app#50]
Tarefas

- [x] Revisar fontes para que fiquem mais harmoniosas

- [x] Revisar responsividade

Critérios 

- [x] App com as melhorias implementadas assim o deixando mais agradável

**Comment by alvesitalo** [comment]
Captura da tela Home melhorada
![Screenshot_1593110172](https://user-images.githubusercontent.com/35741521/85781008-9e790800-b6fb-11ea-808b-adf8d5f81b39.png)
#67

**Comment by alvesitalo** [comment]
No ar na development! 😃
