### ISSUE TITLE
Implementar de fato a feature do mapa

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-app#52]
Tarefas

- [x] Fazer melhorias de estilo

- [x] Usar a localização do user como referencia

Critérios

- [x] Mapa mais agradavel visualmente

- [ ] Numero de pessoas aparecendo no icone do cluster

**Comment by RenatoBrittoAraujo** [comment]
Não consegui fazer o texto de quantas pessoas existem num cluster aparecer, esse texto iria deixar o mapa drásticamente mais lento e, por questões de perfomance, achei preferível substituir por clusters de tamanho variável para representar visualmente a quantidade de pessoas em uma região.
