### ISSUE TITLE
BUG Problemas variados com mapa

### ISSUE THREAD

**Issue by RenatoBrittoAraujo** [proepidesenvolvimento/guardioes-app#62]
**Problemas a se resolver**<br>

- [x] O mapa rederiza os icones com seu tamanho original do arquivo, em celulares com alta resolução, isso faz com que os icones do mapa fiquem muito pequenos.

- [ ] O mapa padrão do IOS é o MapKit, que não aceita configurações de estilo, diferente do Google Maps que aceita. Fazer com que o app em IOS use o mapa do Google Maps.

**Comment by alvesitalo** [comment]
Depois de testes, atualmente não é possível utilizar o Google Maps no iOS, devido a problemas de desempenho e bugs com os clusters.
