### ISSUE TITLE
Data picker com erro (iOS)

### ISSUE THREAD

**Issue by guilacerda** [proepidesenvolvimento/guardioes-app#7]
**Descrição**<br>
As datas do datapicker no ios desaparecem quando você vai escolher a data de nascimento.

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Clique em Cadastrar na tela inicial do app (ios)
2. Clique no picker de birthdate
3. Algumas datas estarão apagadas

**Comportamento Esperado**<br>
Descrição do comportamento esperado pela feature desenvolvida.

**Screenshots**<br>
![image](https://user-images.githubusercontent.com/26297247/78095277-e1ea0180-73ac-11ea-8d51-77bacc79822c.png)

**Informações do Desktop:**
 - OS: ios
 - Versão do OS: 13.3.1

**Comment by gabrieldouurado** [comment]
Problema Resolvido.

O problema ocorre devido ao Dark Apparence presente nos dispositivos IOS.

A solução está implementada no ramo bug/darkModeIOS.
