### ISSUE TITLE
Alert sem conteúdo (erro no login)

### ISSUE THREAD

**Issue by guilacerda** [proepidesenvolvimento/guardioes-app#8]
**Descrição**<br>
Quando você erra o email ou a senha no momento de fazer o login aparece uma mensagem de Alert com a descrição "undefined".

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Clique em Entrar
2. Erre a senha ou email
3. aparecerá o alerta indefinido

**Comportamento Esperado**<br>
O alerta deveria relatar qual foi o erro (Dados incorretos/usuário não existente)

**Screenshots**<br>
![image](https://user-images.githubusercontent.com/26297247/78095434-5329b480-73ad-11ea-88fb-6cf047c64785.png)

**Informações do Desktop:**
 - OS: ios
 - Versão do OS: 13.3.1

**Comment by gabrieldouurado** [comment]
Problema Resolvido!
