### ISSUE TITLE
Falta de opção para diagnóstico de Covid-19

### ISSUE THREAD

**Issue by luisrguerra** [proepidesenvolvimento/guardioes-app#88]
Não tem como uma pessoa que já fez exames e teve diagnóstico positivo para covid-19 avisar no aplicativo essa informação que é bastante relevante .

**Comment by gabrieldouurado** [comment]
O app por si só não pode fornecer diagnósticos. A aplicação possui um algoritmo que identifica possíveis síndromes e dá recomendações para o usuário.
