### ISSUE TITLE
Degradê azul na interface não está bom

### ISSUE THREAD

**Issue by luisrguerra** [proepidesenvolvimento/guardioes-app#89]
O degradê azul que tem na interface na tela de início, no menu lateral e no fundo não está sendo reproduzindo corretamente ( está parecendo como quando se salva um degradê em um formato de imagem de baixa qualidade ). É melhor substituir por uma cor simples.

**Comment by alvesitalo** [comment]
Corrigido com as cores #5DD39E (verde marinho) e #348EAC (azul céu), da nova ID Visual. Na branch **feature/newDesign**
