### ISSUE TITLE
Letra branca nos campos de input (ios)

### ISSUE THREAD

**Issue by guilacerda** [proepidesenvolvimento/guardioes-app#9]
**Descrição**<br>
As letras no ios estão brancas, quase desaparecem quando entram em contraste com o background.

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Digite qualquer informação em um campo de input
2. Letra branca

**Comportamento Esperado**<br>
Ter uma cor que seja possível enxergar.

**Screenshots**<br>
![image](https://user-images.githubusercontent.com/26297247/78095824-55404300-73ae-11ea-9f42-cdec7a452174.png)

**Informações do Desktop:**
 - OS: ios
 - Versão do OS: 13.3.1

**Comment by gabrieldouurado** [comment]
Problema Resolvido.

O problema ocorre devido ao Dark Apparence presente nos dispositivos IOS.

A solução está implementada no ramo bug/darkModeIOS.
