### ISSUE TITLE
O ícone do avatar está muito grande 

### ISSUE THREAD

**Issue by luisrguerra** [proepidesenvolvimento/guardioes-app#91]
O ícone de avatar está muito grande no diário e isto está afetando o aproveitamento de espaço na tela, o calendário está ficando cortado por falta de espaço por conta do tamanho do ícone do avatar. Se ele no diário tivesse metade do tamanho ficaria bem melhor, ele também não está alinhado com o nome da pessoa ( inclusive o sobrenome da pessoa aprece cortado mesmo tendo espaço, seria melhor colocar só o primeiro nome até consertar isso ). No menu lateral o ícone de avatar está muito grande também, metade do tamanho ficaria bom mas na prática no atual estágio do projeto ele é desnecessário no menu lateral, seria melhor aproveitar o espaço para trazer informações uteis. O sobrenome também está aparecendo cortado no menu lateral.

**Comment by alvesitalo** [comment]
Os ícones dos avatares tanto na tela do Diário, quanto no menu lateral foram ajustados. Aparecendo apenas as iniciais no menu lateral quando não há foto do usuário. As alterações podem ser acompanhadas na branch **feature/newDesign**.
