### ISSUE TITLE
Mapeamento de Telas

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-app#92]
Realizar o mapeamento das telas faltantes para implementação do novo design

**Comment by gabrieldouurado** [comment]
Lista de Telas:

- [ ] Tela Inicial;
- [ ] Registrar;
- [ ] Login;
- [ ] Telas de Recuperação de senha;
- [ ] Tela de "Loading";
- [ ] Home;
- [ ] Diário;
- [ ] Conselho;
- [ ] Noticias; 
- [ ] Relato Ruim;
- [ ] Cadastro de Familiar;
- [ ] Maps;
- [ ] Perfil;
- [ ] Ajuda;
- [ ] Rumor;
- [ ] Sobre;
- [ ] Termos e politicas;
- [ ] Tutorial.

**Comment by alvesitalo** [comment]
A implementação de quase todas as telas foi concluída na branch **feature/newDesign**, é necessário testar e vou fazer alguns ajustes também.

**Comment by alvesitalo** [comment]
Concluído, todas as telas com o novo design na branch **development**.
